### ISSUE TITLE
No such variable "s:ft",  key not present in Dictionary: "python"

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/vimcmdline#101] opened 2023-01-22 10:39 UTC
commit 4084e37a7cdc8130ad993db5acba8bbfac654e38

```
Error detected while processing function cmdline#StartApp[3]..cmdline#Init:                                                    
line   34:                                                                                                                     
E108: No such variable: "s:ft"                                                                                                 
Error detected while processing function cmdline#StartApp[6]..cmdline#SetApp:                                                  
line    8:                                                                                                                     
E716: Key not present in Dictionary: "python"                                                                                  
Error detected while processing function cmdline#StartApp[23]..cmdline#Start_Nvim:                                             
line    3:                                                                                                                     
E716: Key not present in Dictionary: "python
```
Configuration
```

let cmdline_app           = {}¬                                                                                                                                                                                        
   829 let cmdline_app['matlab'] = '/snap/bin/octave'¬                                                                                             
~  831 let cmdline_app['python'] = expand('~/anaconda5/bin/ptipython')¬                                                        
~  832 "let cmdline_app['python'] = expand('~/anaconda5/bin/ipython --no-autoindent')¬                                         
   833 let cmdline_app['sh']     = 'bash'¬                                                                                     
   834 let cmdline_app['md']     = 'bash'¬                                                                                     
   835 let cmdline_app['markdown']     = 'bash'¬                                                                               
   836 let cmdline_app['README']     = 'bash'¬                                                                                 
   837 let cmdline_app['rst']     = 'bash'¬                                                                                                                                               
839 let cmdline_vsplit      = 2   " when 1, force vertical split, when 0, force horizontal split¬                           
840 let cmdline_term_width  = 72   " split width, note python allow 79 columns for each line, so the rest can be used for split
841 let cmdline_term_height  = 7  " split height¬                                                                           
842 let cmdline_outhl       = 3 " syntax highlight in the output¬                                                           
843 autocmd FileType python nmap <buffer> <LocalLeader>pp :call VimCmdLineSendCmd(expand('<cword>'))<CR>¬
```

I suspect it might be due to the new commit since if I go back to the last commit then the problem does not occur
```
cd ~/.vim/bundle/vimcmdline$ 
HEAD detached at 9ee3bf2
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ftplugin/md_markdown.vim
```

**Comment by jalvesaq** [comment] 2023-01-22 12:07
I can't replicate the issue, but I'm not using anaconda. I converted the script variables (the ones prefixed with `s:`) into local variables because there was no longer the need to use script variables after putting the code inside a function.

After starting python or any other interpreter, the Vim command `:echo g:cmdline_job` should result in something like this:

```
{'typescript': 0, 'javascript': 0, 'javascriptreact': 0, 'sh': 0, 'sage': 0, 'kdb': 0, 'magma': 0, 'lisp': 0,
 'kotlin': 0, 'go': 0, 'Macaulay2': 0, 'lua': 0, 'matlab': 0, 'python': 3, 'racket': 0, 'clojure': 0, 'julia': 0,
 'typescriptreact': 0, 'swift': 0, 'k': 0, 'haskell': 0, 'scala': 0, 'q': 0, 'prolog': 0, 'ruby': 0}
```

where only the interpreter that was just started would not have `0` as the number of its job.

**Comment by smilesun** [comment] 2023-01-22 12:33
The problem still persistent upon this 

```
commit b4d4accd607fe54515d0354280c29ef1748ef9ed (HEAD -> master, origin/master, origin/HEAD)
Author: Jakson Alves de Aquino <jalvesaq@gmail.com>
Date:   Sun Jan 22 08:54:26 2023 -0300

    Turn script variable into local variable
    See #101
```

when run 
`:echo g:cmdline_job`
I got {'python':15}

I dont know how to dump the output of this echo command to a file so {'python':15} is the only thing i can see.

**Comment by smilesun** [comment] 2023-01-22 12:33
However, the erros in this issue does not affect the use of this plugin

**Comment by jalvesaq** [comment] 2023-01-22 13:46
> I dont know how to dump the output of this echo command to a file so {'python':15} is the only thing i can see.

You did it correctly. It seems that in Anaconda the currently running vim script can't find its own directory.

> However, the erros in this issue does not affect the use of this plugin

This means that the code causing the error was superfluous and could be deleted.

Maybe the issue is fixed now...

**Comment by anasem** [comment] 2023-02-10 12:50
I'm having the same problem only when trying to run python in an external terminal.

`echo g:cmdline_job` gives `{}`. 

I tried with `let g:cmdline_job = 'python'` and somehow it worked

**Comment by jalvesaq** [comment] 2023-02-10 13:29
@anasem, it should be fixed now.

**Comment by anasem** [comment] 2023-02-10 13:30
@jalvesaq indeed, it's fixed!! thank you so much!

**Closed as completed** 2023-02-14 12:23 UTC
